kind: PersistentVolume
apiVersion: v1
metadata:
  name: wordpress-volume
  labels:
    type: local
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.95.100
    path: "/nfs-data/backup"
---

kind: PersistentVolume
apiVersion: v1
metadata:
  name: mysql-volume
  labels:
    type: local
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.95.100
    path: "/nfs-data/backup"
